version: '3'
services:
  db:
    image: postgres:14.5-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
  test-db:
    image: postgres:14.5-alpine
    ports:
      - 5434:5432
    env_file:
      - .env

